// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4cDN99qKSivOnJEWu8nsCb46iIYGEBQ0',
    appId: '1:343986482331:web:4dd6dde585139814a02a3e',
    messagingSenderId: '343986482331',
    projectId: 'childrights-87c9d',
    authDomain: 'childrights-87c9d.firebaseapp.com',
    storageBucket: 'childrights-87c9d.appspot.com',
    measurementId: 'G-7P4BQNNZR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2V_i-rkQ7flbfFdQeFaujjNlfsApRk0',
    appId: '1:343986482331:android:d6316da1120f9ae7a02a3e',
    messagingSenderId: '343986482331',
    projectId: 'childrights-87c9d',
    storageBucket: 'childrights-87c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rCzCy3np7QdshpK-B8_Qskgp-YkGQXo',
    appId: '1:343986482331:ios:ccf69790220b6746a02a3e',
    messagingSenderId: '343986482331',
    projectId: 'childrights-87c9d',
    storageBucket: 'childrights-87c9d.appspot.com',
    iosBundleId: 'com.example.childrightapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rCzCy3np7QdshpK-B8_Qskgp-YkGQXo',
    appId: '1:343986482331:ios:522c88f6b8a1361aa02a3e',
    messagingSenderId: '343986482331',
    projectId: 'childrights-87c9d',
    storageBucket: 'childrights-87c9d.appspot.com',
    iosBundleId: 'com.example.childrightapp.RunnerTests',
  );
}
